### ISSUE TITLE
Publish source?

### ISSUE THREAD

**Issue by sindikat** [takenobu-hs/type-introduction-illustrated#1]
This is a brilliant introduction into types, typeclasses and kinds! I absolutely loved the simple and straightforward explanations of beautiful abstractions behind Haskell's type system. How was the document prepared? Were you using LaTeX or Graphviz or something similar? Is it possible to publish the source for this document?

**Comment by takenobu-hs** [comment]
Thank you very much for your warm comment :)
And, sorry I used PowerPoint. (not TeX or pandoc or, ...)
It's not editable text source code

Regards
